apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    run: hello-world
spec:
  containers:
    - name: teste-1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "0.5"
        requests:
          memory: "64Mi"
          cpu: "0.3"