apiVersion: v1 #--> Versão da API que controla os PODs.
kind: Pod      #--> Recurso a ser criado, neste caso um "POD".
metadata:      #--> Informações de metadata do recurso.
  name: hello-world
  labels:
    run: hello-world
spec:
  containers:
    - name: teste-1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi" #--> Limite máximo de memória a ser utilizado pelo POD.
          cpu: "0.5" #--> Limite máximo a ser utilizado pelo POD.
        requests:
          memory: "64Mi" #--> Kubernetes garante essa quantidade de CPU para o POD.
          cpu: "0.3" #--> Kubernetes garante essa quantidade de Memoria para o POD.