apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx     #--> Declaração da imagem do primeiro container no Pod.
    name: multi-1    #--> Declaração do name para o primeiro container no Pod.
    ports:
    - containerPort: 80
  - image: alpine    #--> Declaração da imagem do segundo container no Pod.
    name: multi-2    #--> Declaração do name para o segundo container no Pod.
    resources:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
