apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: teste
      image: ubuntu
      args:
        - sleep
        - infinity
      volumeMounts:
        - name: teste-1
          mountPath: /teste1
  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi