apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    run: hello-world
spec:
  containers:
    - name: teste-1
      image: nginx
      ports:
        - containerPort: 80
    - name: teste-2
      image: alpine
      args:
      - sleep
      - "1800"